import type { Metadata } from "next";
import "./globals.css";
import { Geist_Mono } from "next/font/google";
import localFont from "next/font/local";

import  Header  from "@/components/Header";
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Saprona_Regular = localFont({
  src: "./fonts/Saprona-Regular.woff",
  display: "swap",
  variable: "--Saprona_Regular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${Saprona_Regular.className}  ${geistMono.className} antialiased text-black`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
